### ISSUE TITLE
1.0.7 - When in full screen view cannot access OC user account drop-down

### ISSUE THREAD

**Issue by MNOCFan** [libasys/calendarplus#139]
Can someone test this in their environment - 
With the latest 1.0.7 pull from Github, when viewing Cal+ in full screen, I lose access to my OC account drop-down in the upper right corner of the screen. After exiting full screen view, I regain access.

**Comment by deMattin** [comment]
You are right!
And not only the account-settings drop-down but also the search field is blocked from usage.

**Comment by deMattin** [comment]
css class .datenavigation is set to 97%
Should be set to absolut 330px.

But this has the disadvantage, that this fixes the display only for wider screens (with showing month in header).
If you resize browser window that much, that display of month disappears, the 330px overlap again.
So there should be a better solution ...

Edit: calandar+ should at this point need some more tests and rework, as this header scales not very well on smaller window sizes.(search filed and settings pull down are a layer behind and search field is not recognized on reducing elements)

**Comment by libasys** [comment]
fixed in next version, thanks for bug reporting!

**Comment by deMattin** [comment]
Everything is accessable now.
But there's an issue remaining with ownlocud's search field sometimes behind "next month arrow" and "month box".
And if you click this search button, if search imput field is in hidden state (small display), it expands also behind calendar+ head stuff.
