### ISSUE TITLE
New Birthdays Calendar subscription on page load

### ISSUE THREAD

**Issue by abyssox** [libasys/calendarplus#153]
Currently using v1.0.9. (Don't know if its relevant: Contact+ v1.0.5).

Everytime i visit the Calendar page or refresh the page, i get one more Birhdays Calendar item.
![2015-09-05__07_44_23](https://cloud.githubusercontent.com/assets/4539953/9697908/612e0d5e-53a2-11e5-90c6-1aaed74062ea.png)
##

**Comment by libasys** [comment]
you have to delete all birthdays subscription and update contacts+ to 1.0.6 (current master)

**Comment by abyssox** [comment]
Contact+ was already current master. Sry, thought it was v1.0.5.
Anyway i deleted all subscriptions but the issue still exists. On every page load i get one more Birthdays subscription.

**Comment by libasys** [comment]
have you access to your database? if yes look on the oc_cldrplus_calendar table! the uri of the birthday calendar should be "birthday_{username}" means for example birthday_tester! and what happend on your installation it increments the calendar to birthday_tester1 and so on!

**Comment by abyssox** [comment]
Yes i see it.
birthday_mario
birthday_mario1
birthday_mario11
birthday_mario111

How can we fix this or where does it come from?

**Comment by libasys** [comment]
can you retest current master, i have done a commit!
https://github.com/libasys/calendarplus/commit/ec9dafc82d18dbcda4fea1e6511453b0179c54cd
which database do you use?

**Comment by abyssox** [comment]
Hmm, unfortunately your fix doesn't work for me. Still have the issue.
I'm using MySQL 5.6.26 with PHP 5.6.12.

**Comment by libasys** [comment]
i have no problems something in error logs? have you deleted the other birthday cals?

**Comment by syt3c** [comment]
hey there,
same prob here (same behavior in the db). imported my calendar.ics in and every pagereload it clones the "birthdays_x". using contacs+1.0.7 and calendar+ 1.1.0
get some err in logs but don't know if its part of the problem: 
Error PHP Array to string conversion at /www/htdocs/myowncloud.com/lib/private/template/functions.php#36

i think it came fromt the contacts+ ? deleted all calendars and its still came up ...

**Comment by syt3c** [comment]
me again ;)
deactivated contacts+ and no more birthday calendars coming up. hopefully helpful

**Comment by libasys** [comment]
no the error comes from the admin settings page itself! Please give me some Info about Environment like Webserver Database and so on! I have tested the New versions with MySQL and sqlite and both Works like expected! The actual versions of calendar+ and contacts+ are on my demo integrated and work like expected! http://demo81.libasyscloud.de

**Comment by syt3c** [comment]
i use oc @ all-inkl.com (hosting), PHP Version 5.5.26, MySQL 5.6.24.
yesterday i importet my contacts but somthing went wrong. deleted all contacts and today i looked at the calendar. still playing with it before it really get going :)

edit: activated the empty contcats+ app and the error starts again. in my logs (loglevel:all) there are some updatemsgs and that: 
Debug DeleteOrphanedSharesJob   0 orphaned share(s) deleted 2015-09-06T23:52:18+02:00
Warning OCP\Share Sharing backend OCA\ContactsPlus\Share\Backend\Contact not registered, OCA\ContactsPlus\Share\Backend\Contact is already registered for cplcontact    2015-09-06T23:52:09+02:00
Warning OCP\Share Sharing backend OCA\ContactsPlus\Share\Backend\Addressbook not registered, OCA\ContactsPlus\Share\Backend\Addressbook is already registered for cpladdrbook   2015-09-06T23:52:09+02:00

**Comment by libasys** [comment]
Have you the normal contacts App. Activated?

**Comment by abyssox** [comment]
Yes, the normal contacts app is activated but i have no errors in the logfile.

**Comment by Nemofly** [comment]
Hello,
i have the same Problem. My System 
OC 8.1.1-3
Newest MySQL version
Ubuntu 15.04
Calendar+ 1.1.0
Contacts+  1.0.7
tasks+       1.0.2
i have an testsystem where only Contacts+ Tasks+ and Calendar+ is activated.
The error only occures if i share a Calendar.
So i have an account "Backup". There i share the calendar to the account "Basti" if i log on in "Basti" and reload the calendar app every refresh one more birthday comes new.
Then i did a new user "Test" i log in an reload the calendar+ app. everything is fine.
If i share a calendar from Backup or Basti account and then login again in "Test" the same birthday error occures.
What can i do?
It was a fresh owncloud installation before!

**Comment by libasys** [comment]
i will investigate!

**Comment by libasys** [comment]
please retest current master of calendar+

**Comment by Nemofly** [comment]
I will test it later and Send Feedback 

Von meinem iPhone gesendet

**Comment by Nemofly** [comment]
So now i tested it, and for me the problem is solved.
only one Birthday is shown.
if you have more after the update delete every Birthday, and after a lot reloads you only have one.
i think it is perfekt now!

**Comment by syt3c** [comment]
Tested the new master. Still the same prob with birthdays..
installed the current contacts+ from github too. but it looks like its a prob with my user. currently I only have two users (john and mike). the 2nd has no problems (john). I deleted the first user but the problem came back as soon as I add a user with the old (mike) name !?

the mysql table looks now like this: 
bdaycpltocal_john
bdaycpltocal_mike
bdaycpltocal_mike1
bdaycpltocal_mike11

in the apps is no data stored and both have been completely cleared and freshly installed.

edit: have added a third user and has the same "birthday"-problem

**Comment by Nemofly** [comment]
Hey, 
Maybee Export your hole calendar and Then Delete all MySQL tables with calendarplus Inside. I think there should be 3 tables.
First deactivate calendarplus. Delete the calendarplus. And Then Try it completly new? 

Von meinem iPhone gesendet

**Comment by syt3c** [comment]
maybe it was an error in the table. I have reinstalled owncloud on my space and now its working :) Added contacts+ after calendar+ and only 1 birthday came up. 

playtime.. ermm no.. bedtime :p 

Edit:
clapped too early. 1st user works fine, the calender of the second dublicates the birthday-tabs again :( as i said, fresh install w/o data.

**Comment by abyssox** [comment]
Same here. I tested the following things:
- deleted all duplicate Birthday Calendars -> New Birthday Calendar subscription after each reload
- deleted Calender+ Apps folder, database tables and installed Calendar+  new from latest git master -> New Birthday Calendar subscription after each reload
- created new test user, logged in, opened Calendar+ Page -> New Birthday Calendar subscription after each reload

@libasys  i can provide you a test account on my owncloud instance if needed.

**Comment by libasys** [comment]
yes please!

**Comment by abyssox** [comment]
@libasys Email is on the way
Please let me know if you need any more information

**Comment by libasys** [comment]
@calis2002 do you use the github version of contacts+? if i add a birthday in your cloud then this isn't displayed on the calendar+ so i think you have an old version of contacts+!

**Comment by abyssox** [comment]
Yes, i use the current master version of Contact+ and Calendar+

**Comment by libasys** [comment]
something in your error logs on the admin settings page?

**Comment by abyssox** [comment]
Unfortunately no

**Comment by libasys** [comment]
please retest current master this fix is included https://github.com/libasys/calendarplus/commit/863073c05f205940ddfab0428581e2c80dc0f2d8

**Comment by syt3c** [comment]
tested the current master (18:00h) -> same prob.

edit: my contactsplus-master is from yesterday ~18:30. tested the creation of a birthday-event in the contacts and yep, it will not appear in the Calendar.

**Comment by abyssox** [comment]
Yes, problem still exists, even with 863073c

**Comment by hoelli** [comment]
Hi!
My help will be little, probably, since I'm quite  a beginner... I just wanted to state, that I have the same problem. I got the newest versions from apps.owncloud.com (not github).
New birthday calendars are created like described above, but in my case not even one birthday from contacts+ appears in calendar+, but I have quite a lot of birthdays stored in my contacts...

I would be very appreciated, if you find a solution for this! :)

If I can do anything to help finding a solution, please let me know.

BR,
Johannes

**Comment by Nemofly** [comment]
Hey,

i´ve got still the same Problem with newest Calendar+ Contacts+ and Tasks+.

Still in a new and fresh instance of owncloud.

**Comment by Mr-HeBo** [comment]
Hey, 

me too. There are no dates of birth displayed (red). 
Each time you open Calendar Plus, an additional birthday calendar (*user_111, *user_1111) is displayed.

![calenda_plus_small](https://cloud.githubusercontent.com/assets/11228598/9958693/d844bb12-5e0c-11e5-811b-0747287dd0fc.png)

OC 8.1.3 (shared hosts) / Contacts Plus 1.0.9 / Calendar Plus 1.1.1  / PHP 5.6.12

**Comment by godfuture** [comment]
I have the same issue.

OC 8.1.3
Calendar+ 1.1.1
Contacts+ 1.0.9

**Comment by libasys** [comment]
Important, please add more information about database and which php version is in use!
Thanks!

**Comment by rolapp** [comment]
The error must in the calendarcontroller.php in this funktion or calling this funktion.

``` php
/**
     * @brief Gets the data of one calendar
     * @param string $uri
     * @return associative array
     */
    public function checkBirthdayCalendarByUri($uri) {
        $calendarInfo = $this->calendarDB->findByUri($uri);

        if($calendarInfo !== null){
            return $calendarInfo['id'];
        }else{
            $newCalId = $this->add($this->userId,$uri,'VEVENT,VTODO,VJOURNAL',null,0,'#C2F9FC',1,'',0);
            CalendarCalendar::editCalendar($newCalId, (string) $this->l10n->t('Birthdays'));

            return $newCalId;
        }

    }
```

The if part is never running the else part with take a new birthday table. I have comment it out a new birthday calender will not create. I think the variable $calendarInfo is every time null. This is the reason of import errors.

**Comment by rolapp** [comment]
## Good News!

I have found the solution. Large and small character in usernames!
![birthday](https://cloud.githubusercontent.com/assets/5871973/9980736/b7ca6182-5fa3-11e5-8c89-90c448c95f14.png)
Birthday calendar from horst is working very well include share the birthday calendar.
Birthday calendar from Steffen have this error. Change the uri from bdaycpltocal_steffen in bdaycpltocal_Steffen. This is also working very well

**Comment by libasys** [comment]
ah perfect now i know the problem! if i check for existing users, i have to use the function to "strtolower"!
Many thanks! good work! next version comes with the bugfix!

**Comment by Mr-HeBo** [comment]
Yes! Thanks rolapp.
The workaround - changing "uri" - works. The birthdays are now displayed and there is no new birthday calendar "**user1xx"!

**Comment by Nemofly** [comment]
Perfect!!
That´s it!
Thanks a lot!! ;)

**Comment by sonst-was** [comment]
According to the change log on apps.owncloud.com this issue has been fixed in 1.1.0 (I dont see that release on github, so I cant verify the dates).

Using owncloud 8.1.3 with Calendar+ 1.1.1 and Contacts 1.0.9 I still have this issue

**Comment by libasys** [comment]
fix for this issue comes today!

**Comment by abyssox** [comment]
@rolapp Thanks! That worked for me too.
As soon as the fix is committed i will close the issue ;)

**Comment by syt3c** [comment]
nice +1

**Comment by godfuture** [comment]
Birthdays still now working for me, when will there be a next contactsplus release so that I could update and be happy?

Cheers

**Comment by godfuture** [comment]
Is it possible to downgrade to the default calendar app? I mean, is the export of calendarplus compatible with calendar default app? This issue drives me nuts and no commits done for long time now.

**Comment by JBScoutDE** [comment]
@godfuture: maybe there will ne no new commits for a longer time. And yes, you can get back to the dedault calebdar app as long as you export your calendard(s) as ICS-file, disable calendar+, activate the default app and import your exported ICS-file(s). Operating on SQL-server-level will not work.
